-- ASTORIE Business Risk Hub 2.0.0 – Core Data Foundation
CREATE TABLE IF NOT EXISTS brh_clients (id BIGSERIAL PRIMARY KEY, ico TEXT, dic TEXT, name TEXT NOT NULL, address TEXT, ares_payload JSONB, business_activity TEXT, turnover NUMERIC, employees_count INTEGER, contact_name TEXT, contact_email TEXT, contact_phone TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now(), archived_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS brh_risk_models (id BIGSERIAL PRIMARY KEY, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT, active BOOLEAN DEFAULT TRUE, version TEXT DEFAULT '1.0', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS brh_cases (id BIGSERIAL PRIMARY KEY, client_id BIGINT REFERENCES brh_clients(id), advisor_id TEXT, title TEXT, status TEXT DEFAULT 'rozpracováno', workflow_step TEXT DEFAULT 'klient', risk_model_id BIGINT REFERENCES brh_risk_models(id), legacy_ref TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now(), closed_at TIMESTAMPTZ, archived_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS brh_master_risks (id BIGSERIAL PRIMARY KEY, risk_model_id BIGINT REFERENCES brh_risk_models(id), risk_key TEXT NOT NULL, name TEXT NOT NULL, category TEXT, description TEXT, default_required BOOLEAN DEFAULT FALSE, default_limit NUMERIC, criticality TEXT DEFAULT 'standard', sort_order INTEGER DEFAULT 100, active BOOLEAN DEFAULT TRUE, UNIQUE(risk_model_id,risk_key));
CREATE TABLE IF NOT EXISTS brh_insurers (id BIGSERIAL PRIMARY KEY, code TEXT UNIQUE, name TEXT NOT NULL, email TEXT, contact_name TEXT, phone TEXT, portal_url TEXT, notes TEXT, active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS brh_risk_aliases (id BIGSERIAL PRIMARY KEY, risk_model_id BIGINT REFERENCES brh_risk_models(id), insurer_id BIGINT REFERENCES brh_insurers(id), risk_key TEXT NOT NULL, alias_name TEXT NOT NULL, source_note TEXT, active BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS brh_case_insurers (id BIGSERIAL PRIMARY KEY, case_id BIGINT REFERENCES brh_cases(id), insurer_id BIGINT REFERENCES brh_insurers(id), custom_insurer_name TEXT, custom_email TEXT, status TEXT DEFAULT 'neodesláno', sent_at TIMESTAMPTZ, answered_at TIMESTAMPTZ, notes TEXT);
CREATE TABLE IF NOT EXISTS brh_requests (id BIGSERIAL PRIMARY KEY, case_id BIGINT REFERENCES brh_cases(id), summary TEXT, territory TEXT, payment_frequency TEXT, client_requirements TEXT, special_terms TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS brh_request_risks (id BIGSERIAL PRIMARY KEY, request_id BIGINT REFERENCES brh_requests(id), risk_key TEXT NOT NULL, requested_limit NUMERIC, required BOOLEAN DEFAULT TRUE, priority TEXT DEFAULT 'standard', notes TEXT);
CREATE TABLE IF NOT EXISTS brh_offers (id BIGSERIAL PRIMARY KEY, case_id BIGINT REFERENCES brh_cases(id), case_insurer_id BIGINT REFERENCES brh_case_insurers(id), insurer_id BIGINT REFERENCES brh_insurers(id), custom_insurer_name TEXT, status TEXT DEFAULT 'čekáme na nabídku', product_name TEXT, annual_premium NUMERIC, deductible NUMERIC, valid_until DATE, advisor_summary TEXT, ai_summary TEXT, is_advisor_recommended BOOLEAN DEFAULT FALSE, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS brh_offer_risks (id BIGSERIAL PRIMARY KEY, offer_id BIGINT REFERENCES brh_offers(id) ON DELETE CASCADE, risk_key TEXT NOT NULL, requested_limit NUMERIC, offered_limit NUMERIC, coverage_status TEXT DEFAULT 'nutno_ověřit', exclusions TEXT, sublimits TEXT, source_reference TEXT, advisor_note TEXT, ai_note TEXT, UNIQUE(offer_id,risk_key));
CREATE TABLE IF NOT EXISTS brh_documents (id BIGSERIAL PRIMARY KEY, case_id BIGINT REFERENCES brh_cases(id), scope TEXT DEFAULT 'case', category TEXT, title TEXT NOT NULL, filename TEXT, file_url TEXT, document_type TEXT, insurer_id BIGINT REFERENCES brh_insurers(id), risk_key TEXT, version TEXT, valid_from DATE, valid_to DATE, uploaded_by TEXT, created_at TIMESTAMPTZ DEFAULT now(), archived_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS brh_text_templates (id BIGSERIAL PRIMARY KEY, owner_user_id TEXT, scope TEXT DEFAULT 'private', status TEXT DEFAULT 'draft', category TEXT, tag TEXT, title TEXT NOT NULL, body TEXT NOT NULL, risk_key TEXT, insurer_id BIGINT REFERENCES brh_insurers(id), created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now(), approved_by TEXT, approved_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS brh_audit_log (id BIGSERIAL PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, old_value JSONB, new_value JSONB, user_id TEXT, created_at TIMESTAMPTZ DEFAULT now());
INSERT INTO brh_risk_models (code,name,description,active,version) VALUES ('BUSINESS_RISKS','Podnikatelská rizika','Základní model pro pojištění podnikatelských rizik ASTORIE',TRUE,'1.0') ON CONFLICT (code) DO NOTHING;
